### ISSUE TITLE
ptxas fatal   : Unresolved extern function '_Z6rforcei'

### ISSUE THREAD

**Issue by moozzz** [klyshko/MT#2]
Hi,

I'm getting this error message when trying to compile the code:

`ptxas fatal   : Unresolved extern function '_Z6rforcei'`

Some additional info:
`cuda 10.0`
`gcc 6.4`
`cmake 3.13`

I'm also using the following NVCC flags:
`set(CUDA_ARCH sm_70)`
`set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS} -arch ${CUDA_ARCH} --ptxas-options=-v)`

Some people have suggested to use the `-dc` option to avoid the above error, but doing so I get this:

`nvcc fatal   : More than one compilation phase specified`

Am I doing something wrong?

**Comment by klyshko** [comment]
Hey,

Try to compile with CUDA_SEPARABLE_COMPILATION flag ON

Let me know how it goes.

Best,
Eugene

**Comment by klyshko** [comment]
add 

"set(CUDA_SEPARABLE_COMPILATION ON)"

to your CMakeLists.txt

**Comment by moozzz** [comment]
Now it worked nicely. Apparently this part of CMakeLists.txt did not do its job correctly on my machine:

```
if (NOT DEFINED CUDA_SEPARABLE_COMPILATION)
  set(CUDA_SEPARABLE_COMPILATION ON)
endif(NOT DEFINED CUDA_SEPARABLE_COMPILATION)
```

**Comment by klyshko** [comment]
I realized it did the same on my machine. If you delete if and endif it’ll work

Eugene Klyshko
